Ajout des sections "Program" et "Speakers"
doxa-tech/rencontredejeunesse pull request #50
Opened 2024-04-12 08:23 UTC by jasiukiewicztymon

Comme demandé j'ai ajouté les sections *Program* et *Speakers*. Pour le design responsif au vu qu'il n'y avait pas plus d'indications que le PDF fourni je me suis permis d'adapter le design responsif de mieux en gardant la cohérence des tailles se font et en gardant une `media-query` à `$mobile-width`.

En ce qui concerne le design responsif du *Program* j'ai utilisé une scrollbar, si cela vous dérange et vous voudriez utiliser quelque chose d'autre veuillez me l'indiquer afin que je puisse effectuer les changements nécessaires.

J'ai remarqué aussi un problème au niveau du `svg` "HIS NAME IS LIFE" qui déborde entre **770 px et 815 px** qui crée une scrollbar. Même si je pense pas que cela a été volontaire, je préfère vous l'indiquer avant de changer quoi qu'il en soit.

2024-04-14 15:05 UTC, nkcr commented
Top, merci!

> Pour le design responsif au vu qu'il n'y avait pas plus d'indications que le PDF fourni je me suis permis d'adapter le design responsif de mieux en gardant la cohérence des tailles se font et en gardant une media-query à $mobile-width.

Yes, parfait.

> En ce qui concerne le design responsif du Program j'ai utilisé une scrollbar, si cela vous dérange et vous voudriez utiliser quelque chose d'autre veuillez me l'indiquer afin que je puisse effectuer les changements nécessaires.

Perso je préfère avoir tous les éléments en vertical, sans scroll horizontal. Ou alors garder comme cela mais en rajoutant une flèche ou quelque chose qui indique clairement qu'on peut scoller en horizontal. 

> J'ai remarqué aussi un problème au niveau du svg "HIS NAME IS LIFE" qui déborde entre 770 px et 815 px qui crée une scrollbar. Même si je pense pas que cela a été volontaire, je préfère vous l'indiquer avant de changer quoi qu'il en soit.

Bien vu! En effet c'est un bug qu'il faudra corriger. 

Sinon j'ai appliqué du formatage automatique sur le code. Si tu utilise VSCode il y a le plugin officiel Astro qui le fait tout seul. Aussi, pour les propriétés CSS veille bien à rajouter une ligner vide entre chaque bloc de définition. Ex:

<table>
<tr>
<td>
❌

```css
p {
  margin: 10px;
  a {
    color: red;
  }
}
a {
  ...
}
```

</td>
<td>
✅

```css
p {
  margin: 10px;

  a {
    color: red;
  }
}

a {
  ...
}
```

</td>
</tr>
</table>

2024-04-14 15:17 UTC, khcr requested changes
Merci pour le travail ! Comme mentionné par Noé, il faudrait juste adapter la version mobile en mettant le programme en vertical ou en indiquant clairement le défilement horizontal.

2024-04-14 15:26 UTC, jasiukiewicztymon commented
Ça joue j'essaie de faire ça ce soir.

2024-04-15 16:39 UTC, khcr approved these changes

2024-04-15 16:40 UTC, merged